theme: minima

minima:
  skin: dark

title: "kamil.blog"
author: "Kamil Przepi√≥rowski"
description: "Putting thoughts into writing."

# Email / Social media user names
github_username: "kamilprz"
linkedin_username: "kamilprz"

# Posts
show_excerpts: false

# Header
header_pages:
  - archive.html
  - bookmarks.md