theme: minima

title: "kamil.blog"
author: "Kamil Przepi√≥rowski"
description: "Putting thoughts into writing."

# Email / Social media user names
github_username: "kamilprz"
linkedin_username: "kamilprz"

# Posts
show_excerpts: false
# date_format: "%Y%m%d"

# Header
header_pages:
  - archive.html
  - bookmarks.md